server {
  listen 80;

  location /api/public/ {
    proxy_pass http://backend:8000;
  }

  location /api/ {
    ${BASIC_AUTH_BLOCK}
    proxy_pass http://backend:8000;
  }

  location / {
    ${BASIC_AUTH_BLOCK}
    proxy_pass http://frontend:5173;
  }
}
